---
- name: Check if Aerospike is already installed
  stat:
    path: /etc/init.d/aerospike
  register: aerospike_service

- include: install_centos.yml
  when: aerospike_service.stat.exists == false and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- include: install_ubuntu.yml
  when: aerospike_service.stat.exists == false and ansible_distribution == 'Ubuntu'